LLNL/conduit

- src/libs/conduit/Node.cpp
- src/libs/conduit/Node.hpp
Remove non const compact() and Node returning compact_to() from Node
resolves #9 (github issue)
> bugfix: remove Node::compact() compact_to()

- src/libs/relay/relay_mpi.cpp
we were using allocs like:
```
int size = ...;
char buffer[size];
```
for MPI buffers.
this commit replaces these with conduit managed buffers
this resolves #29
> task: remove C99 style allocs from relay mpi

- .travis.yml
- src/CMake/CMakeBasics.cmake
- src/docs/sphinx/conf.py.in
- src/libs/conduit/DataArray.cpp
- src/libs/conduit/Generator.cpp
- src/libs/conduit/Node.cpp
- src/libs/conduit/NodeIterator.cpp
- src/libs/conduit/Schema.cpp
- src/libs/conduit/Utils.cpp
- src/libs/conduit/fortran/CMakeLists.txt
- src/libs/conduit/fortran/conduit_fortran.F
- src/libs/relay/python/relay_web_python.cpp
- src/libs/relay/relay_hdf5.cpp
- src/libs/relay/relay_silo.cpp
- src/libs/relay/relay_web.cpp
- src/tests/conduit/t_conduit_array.cpp
- src/tests/conduit/t_conduit_json.cpp
- src/tests/conduit/t_conduit_node_save_load.cpp
- src/tests/conduit/t_conduit_utils.cpp
add several fixes for unused vars
add a few fixes for unused functions
suppress c <-> fortran binding warnings
> address several compiler warnings

- src/libs/conduit/DataType.cpp
- src/libs/conduit/DataType.hpp
- src/libs/relay/relay_hdf5.cpp
- src/tests/conduit/t_conduit_datatype_tests.cpp
- src/tests/relay/t_relay_io_hdf5.cpp
> enh: add auto endian convert on relay hdf5 read

- .gitignore
- package.py
- scripts/uberenv/uberenv.py
- src/docs/sphinx/building.rst
- src/examples/docker/ubuntu/Dockerfile
- src/examples/docker/ubuntu/example_build.sh
- src/examples/docker/ubuntu/example_run.sh
> enh: fix to uberenv and reorg of docker example

- src/thirdparty_builtin/civetweb-0a95342/CMakeLists.txt
> bugfix: avoid new civet clang pragma warnings

- src/libs/relay/conduit_relay_web.cpp
- src/libs/relay/conduit_relay_web_node_viewer_server.cpp
fixed problem with function that locates the web root
(it was using the wrong about() routine)
> bugfix: fix web root detection for installs

- src/libs/relay/conduit_relay_hdf5.cpp
use property list to set hdf5 libver to latest on file create and open
resolves: #173
> use plist to hdf5 libver to latest

- src/CMake/thirdparty/SetupHDF5.cmake
> add extra abs_path check to hdf5 cmake sanity checks

- src/CMake/thirdparty/SetupHDF5.cmake
fixes a problem with the abs path checking added in #177
> fix get_filename_component call

- appveyor.yml
- src/libs/relay/conduit_relay_mpi.cpp
Add recipe for using msmpi in appveyor following @kennyweiss's solution for blt. 
resolves #205
> update blt and add mpi testing via msmpi on appveyor

- src/libs/relay/conduit_relay_io.cpp
- src/tests/relay/t_relay_io_basic.cpp
missed pushing needed commit for #219
> extra dive letter logic

- src/libs/conduit/conduit_node.cpp
- src/libs/conduit/conduit_node.hpp
> use const for ptr variants of set and set path

- src/libs/blueprint/python/conduit_blueprint_python.cpp
- src/libs/conduit/python/conduit_python.cpp
- src/libs/conduit/python/conduit_python.hpp
- src/libs/relay/python/conduit_relay_python.cpp
> expand python capsule iface for Node

- src/libs/blueprint/conduit_blueprint_mesh_examples.cpp
> remove incorrect entry 'domain' from braid mesh bp example

- src/cmake/CMakeBasics.cmake
> fix: DIRT != DIR

- appveyor.yml
- scripts/ci/travis-test-build-examples-vs-install.sh
- src/CMakeLists.txt
- src/examples/CMakeLists.txt
- src/examples/python/conduit_python_example.py
> add python example, add install of examples

- scripts/uberenv/uberenv.py
> update uber to support osx sdk that doesn't match current osx ver

- src/docs/sphinx/blueprint_mesh.rst
- src/libs/blueprint/conduit_blueprint_mesh.cpp
- src/libs/blueprint/conduit_blueprint_mesh.hpp
- src/libs/blueprint/conduit_blueprint_mesh_examples.cpp
- src/tests/blueprint/t_blueprint_mesh_examples.cpp
- src/tests/blueprint/t_blueprint_mesh_verify.cpp
> mesh blueprint: add implicit point topology docs and example

- src/docs/sphinx/building.rst
* more details about CMake up front
* update uberenv option docs
> update docs for building

- src/libs/conduit/conduit_utils.cpp
- src/libs/conduit/conduit_utils.hpp
- src/libs/conduit/python/conduit_python.cpp
- src/libs/relay/CMakeLists.txt
- src/libs/relay/conduit_relay_io.cpp
- src/libs/relay/conduit_relay_io.hpp
- src/libs/relay/conduit_relay_io_convert_exe.cpp
- src/libs/relay/python/conduit_relay_io_python.cpp
- src/tests/relay/CMakeLists.txt
- src/tests/relay/python/t_python_relay_io.py
- src/tests/relay/t_relay_io_file_sizes.cpp
- src/tests/relay/t_relay_io_hdf5.cpp
add unit test that probes output files sizes for all relay protocols
add relay io convert util
relay io generic save, add options param
> a few relay io hdf5 enhancements

- src/docs/sphinx/blueprint_mesh.rst
- src/docs/sphinx/index.rst
- src/tests/docs/t_conduit_docs_blueprint_demos.cpp
> provide simple uniform mesh bp example and docs refactor

- src/libs/blueprint/conduit_blueprint_mesh.cpp
- src/libs/conduit/conduit_node.cpp
- src/tests/blueprint/t_blueprint_mesh_verify.cpp
- src/tests/conduit/t_conduit_node.cpp
throw error for empty path fetch 
improve blueprint index gen logic to avoid empty path fetch
> avoid empty path fetch

- src/libs/blueprint/conduit_blueprint_mesh.cpp
- src/tests/blueprint/t_blueprint_mesh_verify.cpp
change mesh bp verify cascade to avoid losing info about 
multi domain failures
> bug fix for mesh blueprint verify 

- src/libs/conduit/c/conduit_node.h
- src/libs/conduit/c/conduit_node_c.cpp
- src/libs/conduit/cmake/BitwidthMapping.cmake
- src/libs/conduit/conduit_bitwidth_style_types.h.in
- src/libs/conduit/conduit_data_array.cpp
- src/libs/conduit/conduit_data_array.hpp
- src/libs/conduit/conduit_data_type.cpp
- src/libs/conduit/conduit_data_type.hpp
- src/libs/conduit/conduit_node.cpp
- src/libs/conduit/conduit_node.hpp
- src/libs/conduit/fortran/conduit_fortran.F90
- src/libs/conduit/fortran/conduit_fortran_bitwidth_style_types.inc.in
- src/tests/conduit/c/t_c_conduit_node_set.cpp
- src/tests/conduit/t_conduit_datatype_tests.cpp
- src/tests/conduit/t_conduit_node.cpp
- src/tests/conduit/t_conduit_node_compare.cpp
- src/tests/conduit/t_conduit_node_set.cpp
- src/tests/conduit/t_conduit_node_to_value.cpp
expand type system to support systems char is unsigned
> upgrade type system with more explicit signed support

- src/docs/sphinx/building.rst
fixed typo in sphinx ref to quick_start
> fix docs typo with sphinx ref

- src/libs/conduit/conduit_node.cpp
- src/libs/conduit/conduit_node.hpp
- src/libs/conduit/conduit_schema.cpp
- src/libs/conduit/conduit_schema.hpp
- src/libs/conduit/python/conduit_python.cpp
- src/tests/conduit/python/t_python_conduit_node.py
- src/tests/conduit/python/t_python_conduit_schema.py
- src/tests/conduit/t_conduit_node.cpp
- src/tests/conduit/t_conduit_schema.cpp
+ python interface methods
+ c++ and python unit tests
> add rename_child method to Schema and Node

- src/libs/conduit/conduit_node.cpp
- src/tests/relay/t_relay_io_basic.cpp
> avoid alloc of zero bytes in Node compact_to

- src/cmake/thirdparty/SetupHDF5.cmake
> add extra hdf5 cmake hint for windows

- CHANGELOG.md
- src/libs/blueprint/conduit_blueprint_mesh_examples.cpp
- src/libs/conduit/conduit_node.cpp
- src/tests/blueprint/t_blueprint_mesh_examples.cpp
- src/tests/blueprint/t_blueprint_mesh_transform.cpp
- src/tests/conduit/c/t_c_conduit_node.cpp
- src/tests/conduit/t_conduit_node.cpp
> memcheck pass

- CHANGELOG.md
- src/docs/sphinx/index.rst
add markus to contribs list
add simple changelog entry for ZFP support
> add zfp info

- src/libs/conduit/conduit_generator.cpp
- src/libs/conduit/conduit_node.cpp
- src/tests/conduit/t_conduit_generator.cpp
- src/tests/conduit/t_conduit_yaml.cpp
> avoid yaml bool literal parsing, keep as string

- CHANGELOG.md
- src/libs/relay/conduit_relay_io_hdf5.cpp
- src/libs/relay/conduit_relay_io_hdf5_api.hpp
- src/tests/relay/t_relay_io_hdf5.cpp
> relay: expand range of strings that can be read from hdf5 files

- CHANGELOG.md
- src/libs/conduit/python/conduit_python.cpp
- src/tests/conduit/python/t_python_conduit_node.py
> add support for setting numeric py lists and tuples

- src/CMakeLists.txt
- src/cmake/SetupIncludes.cmake
> shift def of build time includes to before setting up tpls

- CHANGELOG.md
- src/libs/conduit/python/conduit_python.cpp
- src/tests/conduit/python/t_python_conduit_node.py
> python: allow node.set_external to take a conduit node

- CHANGELOG.md
- src/libs/conduit/conduit_node.cpp
- src/libs/conduit/conduit_node.hpp
> add proto detect to Node load and save

- CHANGELOG.md
- src/libs/conduit/conduit_error.cpp
- src/tests/conduit/CMakeLists.txt
- src/tests/conduit/t_conduit_error.cpp
- src/tests/conduit/t_conduit_node_save_load.cpp
> print error messages in a way that is nicer for humans

- src/CMakeLists.txt
- src/docs/sphinx/index.rst
- src/docs/sphinx/t_conduit_docs_tutorial_numeric_out.txt
- src/docs/sphinx/tutorial_cpp_numeric.rst
- src/tests/docs/t_conduit_docs_tutorial_numeric.cpp
- src/thirdparty_builtin/rapidjson/CMakeLists.txt
- src/thirdparty_builtin/rapidjson/example/CMakeLists.txt
- src/thirdparty_builtin/rapidjson/test/perftest/CMakeLists.txt
- src/thirdparty_builtin/rapidjson/test/unittest/CMakeLists.txt
> minor doc cleanup and remove CMP0054

- CHANGELOG.md
resolves #503 
Newer blt avoids rpath de-dupe issue.
> update to blt v0.3.0

- CHANGELOG.md
- src/docs/sphinx/relay_io.rst
- src/libs/relay/conduit_relay_io_handle.cpp
- src/libs/relay/conduit_relay_io_handle_api.hpp
- src/tests/relay/t_relay_io_handle.cpp
> add open mode option to RelayIOHandle

- CHANGELOG.md
- appveyor.yml
- scripts/uberenv/packages/conduit/package.py
- scripts/uberenv/project.json
- src/cmake/SetupTests.cmake
- src/docs/sphinx/relay_mpi.rst
- src/docs/sphinx/t_conduit_docs_python_tutorial_relay_mpi_examples_out.txt
- src/libs/relay/python/CMakeLists.txt
- src/libs/relay/python/conduit_relay_mpi_python.cpp
- src/libs/relay/python/conduit_relay_python_exports.h.in
- src/libs/relay/python/py_src/__init__.py
- src/libs/relay/python/py_src/mpi/__init__.py
- src/libs/relay/python/setup.py
- src/tests/docs/CMakeLists.txt
- src/tests/docs/t_conduit_docs_tutorial_python_relay_mpi_examples.py
- src/tests/relay/python/CMakeLists.txt
- src/tests/relay/python/t_python_relay_mpi.py
> py: add initial conduit.relay.mpi module and tests

- CHANGELOG.md
- src/libs/blueprint/conduit_blueprint_mesh_examples.cpp
- src/tests/blueprint/t_blueprint_mesh_examples.cpp
> add output of adjset_uniform example to hdf5

- src/docs/sphinx/building.rst
Can't say I never did anything for you
> doc: typo in bootstrap host-config

- src/libs/blueprint/conduit_blueprint_mpi_mesh.cpp
- src/tests/blueprint/t_blueprint_mpi_mesh_verify.cpp
> mesh bp gen index, bcast result to all ranks

- CHANGELOG.md
- src/libs/conduit/python/conduit_python.cpp
- src/libs/relay/python/py_src/__init__.py
- src/tests/conduit/python/t_python_conduit_node.py
> python: bug fix for Node.set with complex strided multi-d views

- CHANGELOG.md
- src/libs/relay/conduit_relay_mpi.cpp
- src/libs/relay/conduit_relay_mpi.hpp
- src/tests/relay/t_relay_mpi_test.cpp
> add relay::mpi:wait and relay::mpi:wait_all

- CHANGELOG.md
- src/docs/sphinx/blueprint_mesh.rst
- src/libs/blueprint/conduit_blueprint_mesh_examples.cpp
- src/libs/relay/python/py_src/__init__.py
- src/tests/relay/adios_test_utils.hpp
> mesh bp fix struct topo optional origin names

- src/libs/blueprint/conduit_blueprint_mesh.cpp
This PR removes `dim_sizes` object from TopologyMetadata. 
`dim_sizes` logic was originally added to handle the case where if given a `shape: polyhedral` Node, the `elements/sizes` field needed to be initialized for the polygonal Node of `dim_topos` , the topology cascade.
Besides the polygonal 2D index, the rest of `dim_sizes` is uninitialized.
`dim_sizes` logic has been replaced for logic that handles the specific polyhedral Node input case.
> Remove dim_sizes from TopologyMetadata

- src/cmake/SetupTests.cmake
- src/cmake/thirdparty/SetupPython.cmake
- src/libs/blueprint/python/CMakeLists.txt
- src/libs/conduit/python/CMakeLists.txt
- src/libs/relay/python/CMakeLists.txt
> add cmake folder props for python targets
