LLNL/conduit

README.md
Managed to break one of them in #1 and also, with the DNS alias I set up, now we can use http://software.llnl.gov/... instead of http://llnl.github.io/... for project links.
=> Fixed / updated links in README

src/CMake/CMakeBasics.cmake
Client code should not need to link them b/c we are using
PRIVATE linkage. In fact, client code not using cmake works
with out linking to them, however the remain a dependice for
client code using cmake and importing conduit's cmake targets.
resolves #14 (github)
=> bugfix: reenable install of libcivet and libbb64

src/CMake/thirdparty/SetupPython.cmake, src/docs/sphinx/building.rst, src/libs/conduit/python/CMakeLists.txt, src/libs/relay/python/CMakeLists.txt
Added PYTHON_MODULE_INSTALL_PREFIX CMake option for specifying
the destination path for the python modules.
This will resolve GitHub Issue #17
=> enh: add python module install path option

scripts/uberenv/packages/mpich/package.py, scripts/uberenv/packages/python/package.py, scripts/uberenv/packages/python3/package.py
* roll back to earlier mpich version
The 3.2 version source disappeared from mpich's website,
though it's back online we don't have any pressing need
for the newer version.
* avoid make -j builds by spack for  python2 and python3
=> uberenv: defensive tweaks to mpich and py packages

src/libs/conduit/CMakeLists.txt, src/libs/relay/CMakeLists.txt, src/tests/conduit/CMakeLists.txt, src/tests/conduit/c/CMakeLists.txt, src/tests/docs/CMakeLists.txt, src/tests/thirdparty/CMakeLists.txt, src/tests/thirdparty/t_civetweb_smoke.cpp, src/thirdparty_builtin/civetweb-1.8/CMakeLists.txt, src/thirdparty_builtin/libb64-1.2.1/CMakeLists.txt
to avoid potential conflicts for system installs:
renamed b64 to conduit_b64
renamed civetweb to conduit_civetweb
These are only used internally, but are always installed -- due
to github issue #16 
This will resolve #18
=> enh: rename b64 and civetweb targets and libs

src/libs/conduit/Schema.cpp, src/libs/conduit/Schema.hpp, src/tests/conduit/t_conduit_schema.cpp
if the Schema represents an object, this method
allows you to get a child's name by index.
if the Schema is not an object, or the index is bad
it returns an empty string.
This commit resolves #13.
=> enh: add Schema::child_name(idx)

src/libs/blueprint/CMakeLists.txt, src/libs/conduit/CMakeLists.txt, src/libs/conduit/fortran/CMakeLists.txt, src/libs/relay/CMakeLists.txt, src/thirdparty_builtin/civetweb-1.8/CMakeLists.txt, src/thirdparty_builtin/libb64-1.2.1/CMakeLists.txt
to avoid potential conflicts during system installs
this resolves #24
=> enh: install headers to subdir include/conduit

.gitignore, .travis.yml, src/docs/sphinx/building.rst, src/examples/using-with-cmake/CMakeLists.txt, src/examples/using-with-cmake/FindConduit.cmake, src/examples/using-with-cmake/example.cpp, src/examples/using-with-make/Makefile, src/examples/using-with-make/example.cpp
Added simple examples that demonstrate how to include conduit
in CMake-based project, and via a Makefile.
=> enh: added examples of using installed conduit

src/tests/blueprint/t_blueprint_mesh_examples.cpp
removes an extra "/mesh"  in the bp index for all of the example fields.
=> bugfix: fix bad path in ex blueprint mesh indices

src/libs/blueprint/blueprint_mesh_examples.cpp, src/libs/relay/relay_silo.cpp, src/tests/blueprint/t_blueprint_mesh_examples.cpp
adds a point-centered vector field to the 2d and 3d braid example
meshes, and hdf5 output.
=> enh: add vector field to blueprint example meshes

src/libs/blueprint/blueprint_mesh_examples.cpp, src/libs/relay/relay_silo.cpp, src/tests/blueprint/t_blueprint_mesh_examples.cpp
adds a 2d and 3d example topologies that use lines.
these examples create meshes with lines elements that simply
represent the outline of the braid quads (2d), or hexs (3d) using
a naive approach.
With this approach there are lines that overlap spatially. This
was done so we could reuse the existing helper functions that
generate the values for the example element centered scalar field.
With more effort, we could create a better sample mesh.
=> enh: add lines topo examples to mesh bp

src/libs/relay/relay_hdf5.cpp, src/tests/relay/CMakeLists.txt, src/tests/relay/t_relay_io_hdf5.cpp, src/tests/relay/t_relay_io_hdf5_read_and_print.cpp
adds references paths to all realy_hdf5 calls and leverage
these in compatibility and error checks.
Now the full path to where the error occurs is included
in the error message.
also added a helper that reads an hdf5 file using relay and prints
the resulting conduit hierarchy.
This resolves #19
=> enh: propagate ref_paths to all relay_hdf5 calls

src/libs/conduit/CMake/BitwidthChecks.cmake, src/libs/conduit/Node.cpp, src/libs/conduit/Node.hpp, src/libs/conduit/Utils.cpp
fix constness of private long long and long double methods
fix use of CONDUIT_WARNING instead of CONDUIT_WARN in a windows
only if def block
add extra checks to the  long case in bitwidth style checks so it can be
moved to after other types (if necessary)
=> bugfix: windows logic for warnings and long long

src/libs/relay/relay_web_node_viewer.cpp
fix bug with handling of the --address command line argument
for the conduit node viewer.
=> bugfix: fix parse cmd line arg for node viewer

src/libs/conduit/Utils.cpp, src/thirdparty_builtin/civetweb-1.8/src/civetweb.c
code to fix the civetweb clock_gettime osx 10.12 issue from:
https://github.com/civetweb/civetweb/blob/master/src/civetweb.c
Commit: 3b6461d2a02cc0c9940d9502f56da3541037f5ba
This resolves #59
=> bugfix: add osx 10.12 clock_gettime from civetweb

src/libs/blueprint/blueprint_mcarray.cpp, src/libs/blueprint/blueprint_mesh.cpp, src/libs/conduit/Node.cpp, src/libs/conduit/Node.hpp, src/libs/conduit/NodeIterator.cpp, src/libs/conduit/NodeIterator.hpp, src/libs/conduit/Schema.cpp, src/libs/conduit/Schema.hpp, src/libs/conduit/python/conduit_python.cpp, src/libs/relay/relay_hdf5.cpp, src/libs/relay/relay_silo.cpp, src/tests/blueprint/t_blueprint_mcarray_examples.cpp, src/tests/blueprint/t_blueprint_mesh_examples.cpp, src/tests/conduit/python/t_python_conduit_node.py, src/tests/conduit/python/t_python_conduit_node_iterator.py, src/tests/conduit/t_conduit_node_iterator.cpp, src/tests/conduit/t_conduit_node_paths.cpp, src/tests/conduit/t_conduit_schema.cpp
change Node::paths() to Node::child_names()
change Schema::paths() to Schema::child_names()
remove copy out variants of Node::paths and Schema::paths
return const ref to empty string vec for case where Node
is not in the object role (avoid exception)
change NodeIterator::path() to NodeIterator::name()
=> enh: use name instead of paths in several methods

src/libs/blueprint/blueprint_mesh.cpp, src/tests/blueprint/CMakeLists.txt, src/tests/blueprint/t_blueprint_mcarray_examples.cpp, src/tests/blueprint/t_blueprint_mcarray_verify.cpp, src/tests/blueprint/t_blueprint_mesh_verify.cpp
The changes in this pull request will add test cases to verify the correctness of the `conduit::blueprint::mcarray::verify` and `conduit::blueprint::mesh::verify` functions in simple cases not covered by the existing example tests (see  #55 for more information).
=> tests: add test cases for mcarray/mesh verify functions

src/libs/relay/conduit_relay_web_node_viewer.cpp
--doc-root command line option can be used to change where on the fs the http looks for files to serve.
=> add doc root option to node viewer

scripts/uberenv/packages/openssl/package.py
to avoid version fetches that occur in the pegged ver
of spack develop we are using
=> uberenv: use custom openssl

src/libs/blueprint/conduit_blueprint_mesh.cpp, src/tests/blueprint/t_blueprint_mesh_verify.cpp
The values for rectilinear coordsets aren't necessarily
mcarrays, since they use an implied cross product of
separate arrays to define the actual coordset.
This update changes verify for the rectilinear coordset
case  to check that "values" has numeric children, instead
of checking that "values" is an mcarray.
=> bugfix: fix bug in mesh bp recti coord set verify

src/libs/conduit/conduit_node.cpp, src/libs/conduit/conduit_node.hpp
the typical use case of this is a shallow copy
the node structure is duplicated, but e data is zero-copied.
For this use case you want a const guarantee for the node
structure of the passed ref.
=> enh: set_external now takes const Node ref

src/CMake/SetupDocs.cmake, src/docs/sphinx/building.rst, src/docs/sphinx/conf.py, src/docs/sphinx/tutorial_ownership.rst, src/docs/sphinx/tutorial_update.rst
modify sphinx cmake macro to support both a cmake config'd
(config.py.in) and standard config.py
move to use config.py so we can more easily leverage read the docs
fix a few typos
this will resolve #100
=> enh: directly use config.py for sphinx docs

src/CMake/CMakeBasics.cmake, src/libs/conduit/CMakeLists.txt, src/libs/conduit/conduit_utils.cpp, src/libs/conduit/conduit_utils.hpp, src/libs/relay/CMakeLists.txt, src/libs/relay/conduit_relay_web.cpp, src/tests/CMakeLists.txt, src/tests/conduit/t_conduit_utils.cpp, src/tests/t_config.hpp.in
also expose the proper platform specific path separator
=> enh: add file system path split helpers

src/thirdparty_builtin/civetweb-0a95342/src/civetweb.c
add gcc version ifdef guards to avoid errors with
newer gcc pragma support, allowing us to build using
gcc 4.4.7
=> bugfix: guards to allow civet to build w/ old gcc

src/libs/relay/conduit_relay_hdf5.cpp, src/libs/relay/conduit_relay_hdf5.hpp
added conduit dtype to hdf5 dtype helpers to the relay hdf5 interface
removed unreachable empty case logic in hdf5_dtype_to_conduit_dtype
This will resolve #125  and #126
=> enh: expose conduit dtype to hdf5 dtype helpers

src/tests/blueprint/t_blueprint_mesh_examples.cpp
fixes typo (passing y_npts as z_npts) that caused the 2d
uniform braid example to be 3d.
=> bugfix: fix error making 2d braid uniform 3d

scripts/uberenv/packages/uberenv-conduit/package.py
=> fix typo in uberenv conduit pkg python support

src/docs/sphinx/blueprint_mesh.rst
Resolves #151 
number_of_domains was only mentioned in the docs, end even though it was optional -- it not checked in any verify methods, so this is an easy fix.
=> remove uness number of domains ref in docs

src/libs/conduit/conduit_utils.cpp, src/tests/conduit/t_conduit_json_sanitize.cpp
fixed bug with json sanitize, where the 'e' in json literals
using sci notation would be escaped, causing parse errors.
resolves #158
=> fix json sanitize bug with sci notation literals

src/libs/blueprint/c/conduit_blueprint.h, src/libs/blueprint/c/conduit_blueprint_c.cpp, src/libs/blueprint/c/conduit_blueprint_mcarray.h, src/libs/blueprint/c/conduit_blueprint_mcarray_c.cpp, src/libs/blueprint/c/conduit_blueprint_mesh.h, src/libs/blueprint/c/conduit_blueprint_mesh_c.cpp, src/libs/conduit/c/conduit_node.h, src/libs/conduit/c/conduit_node_c.cpp
changes all instances of bool to in in the c-api
for conduit + blueprint.
bool is in C99, but requires include of stdbool.h
using int instead of bool will make c-api easier
to use on a wider set of compilers.
=> use int instead of bool in c-api for wider compat

src/libs/conduit/conduit_node_iterator.cpp, src/libs/conduit/conduit_node_iterator.hpp, src/tests/conduit/t_conduit_node_iterator.cpp
The best way to obtain an iterator to  a node's children is via the `children()` method, for example:
```
NodeIterator itr = n.children();
NodeConstIterator citr = n.children();
```
However we also want to support using iterator constructors directly.
Prior to this update, the constructors only supported a pointer to a node:
`NodeIterator itr(&n);`
Which is awkward, given we usually write algorithms using Node refs.
This update adds constructors to support:
```
NodeIterator itr(n);
NodeConstIterator citr(n);
```
=> add iterator constructors that take node refs

src/libs/conduit/conduit_node.cpp, src/tests/conduit/t_conduit_node_set.cpp
Add a reset() to the object and list cases to avoid creating
bad nodes.
for the future: we would like to propagate sets in a way
that preserves existing schema and allocs if possible.
This will require adding some tricky logic, so the
this solution restores correctness.
=> fix bug with Node::set_node()

src/CMake/thirdparty/SetupHDF5.cmake
further harden the cmake hdf5 sanity check:
HDF5_INCLUDE_DIRS may also include paths to external lib headers (such as szip), so we check that *at least one* of the includes listed in HDF5_INCLUDE_DIRS exists in the HDF5_DIR specified.
=> cmake hdf5 sanity check, now with more sanity

src/libs/relay/conduit_relay_hdf5.cpp, src/libs/relay/conduit_relay_hdf5.hpp
adds hdf5_open_file_for_write and hdf5_open_file_for_read
to conduit::relay::io.
These methods open hdf5 files using conduit's desired hdf5 property
list settings.
=> add hdf5 file open headers to relay api

src/libs/conduit/conduit_node.cpp, src/libs/conduit/conduit_schema.cpp
Add quotes to child name in error message for non-existent child fetch.
This will resolve #201
=> add quotes to child name in non-exist error msg

src/libs/conduit/conduit_node.cpp, src/tests/conduit/t_conduit_serialize.cpp
Fixes #226 reported by @tomvierjahn
Also adds simple test for the issue, adapted from @tomvierjahn's tests
There was an indexing issue with the compact case, causing the offset not to be used in memcpy.
=> fix data indexing error in serialize

src/libs/relay/conduit_relay_silo.cpp
The changes in this pull request fix compilation errors introduced into the Silo reader/writer code as a result of the refactoring performed in #244.  These changes re-enable compilation of Silo-enabled versions of Conduit.
=> fix compilation bug in silo reader/writer code

src/libs/conduit/conduit_node.cpp, src/tests/conduit/t_conduit_node_save_load.cpp
Otherwise, the file might not load all the requested bytes.
=> Bugfix: Node:load() needs to open its file in binary mode.

src/libs/conduit/conduit_node.cpp, src/tests/conduit/t_conduit_node_compare.cpp
The changes in this pull request fix a bug in the `Node::diff` implementation that caused it to fail when comparing two nodes that had string data with non-zero offset values. This pull request also amends the `Node::diff` test cases to validate that these fixes work properly.
=> Bugfix: Node::diff fails for string data with offsets

src/libs/blueprint/conduit_blueprint_mesh.cpp
The changes in this pull request fix the error messages provided when the Blueprint code encounters an improper reference (see #275 for details).
=> fix report messages for blueprint references

src/docs/sphinx/blueprint_mesh.rst
The changes in this pull request fix a minor typo in the Blueprint documentation related to the specification for spherical rectilinear coordinate sets.
=> fix typo in the blueprint documentation

src/cmake/thirdparty/SetupRapidJSON.cmake
This allows conduit to be included as a submodule in another CMake project.
=> Use PROJECT_SOURCE_DIR for RapidJSON include

src/libs/conduit/conduit_node.cpp, src/tests/conduit/t_conduit_node_set.cpp
resolves bug where full contents of std::vector data weren't copied when one of the c native gap method implementations was used
=> fix bug in std::vect gap methods and add more tests

src/libs/relay/conduit_relay_hdf5.cpp
=> relay io hdf5: only use libver latest for hdf5 1.8

src/libs/blueprint/conduit_blueprint_mesh.cpp, src/tests/blueprint/t_blueprint_mesh_transform.cpp
The changes in this pull request fix a host of issues in the `conduit::blueprint::mesh::{coordset|topology}::to_*` functions associated with processing inputs containing non-standard bit width types. These bugs would cause these functions to crash when users attempted to pass mesh data with anything other than `{u}int32` and `float64` type data. With these fixes in place, mesh data of any viable type can be passed through these transformation interfaces.
=> fix issues w/ non-standard bit widths in blueprint transforms

CHANGELOG.md, src/libs/relay/conduit_relay_mpi.cpp, src/tests/relay/t_relay_mpi_test.cpp
Schema::compatible() doesn't give is the green light to zero copy complex types, so we need more checks to avoid crashes.
=> fix crash in relay mpi bcast with non empty recv nodes

src/libs/conduit/conduit_node.cpp, src/libs/conduit/conduit_node.hpp, src/libs/conduit/conduit_schema.cpp, src/libs/conduit/conduit_schema.hpp, src/tests/conduit/t_conduit_json.cpp, src/tests/conduit/t_conduit_yaml.cpp
The changes in this pull request modify the `conduit::Node` and `conduit::Schema` classes so that their "to string" operations (e.g. `to_json`, `to_yaml`) have explicit default versions are available (i.e. versions wherein all arguments are filled with their default values and no additional arguments are accepted). The primary reason to include these functions is for better compatibility with debugging tools (e.g. totalview, gdb), which often have difficulties automatically filling in default string arguments.
The full list of changes in this pull request is as follows:
=> add explicit default "to string" operations

CHANGELOG.md, src/libs/conduit/c/conduit_node.h, src/libs/conduit/c/conduit_node_c.cpp, src/libs/conduit/fortran/conduit_fortran.F90, src/libs/conduit/fortran/conduit_fortran_obj.f90, src/tests/conduit/c/t_c_conduit_node.cpp, src/tests/conduit/fortran/t_f_conduit_node.f90, src/tests/conduit/fortran/t_f_conduit_node_int.f90, src/tests/conduit/fortran/t_f_conduit_node_obj.f90
=> add several more conduit node methods to the fortran api

src/cmake/thirdparty/SetupHDF5.cmake, src/config/conduit_setup_deps.cmake
to help downstream cmake users of conduit
=> call findhf5 in exported targets 

src/docs/sphinx/blueprint_mesh.rst
The changes in this pull request address the documentation bug outlined in #417.
=> fix typos and wording in poly topology documentation

src/CMakeLists.txt, src/docs/sphinx/building.rst
=> Add CONDUIT_ENABLE_TESTS

src/config/ConduitConfig.cmake.in
When used through vcpkg, several LIBRARY_DIR variables get set to the value `${_IMPORT_PREFIX}`.  This change copies the logic for setting up _IMPORT_PREFIX to before it gets used.
Many thanks to @white238 for his help on this.
=> Set _IMPORT_PREFIX, as needed by vcpkg machinery

CHANGELOG.md, src/libs/conduit/conduit_log.cpp, src/libs/conduit/conduit_log.hpp, src/tests/conduit/CMakeLists.txt, src/tests/conduit/t_conduit_log.cpp
The changes in this pull request add two filtering functions for log nodes output by Conduit in order to assist users with isolating and parsing critical log output. The exact set of functions added and their associated changes are as follows:
=> add filter functions for log nodes

CHANGELOG.md, src/libs/relay/conduit_relay_io_hdf5.cpp, src/tests/relay/t_relay_io_hdf5.cpp
=> relay hdf5: use H5F_ACC_RDONLY for is_hdf5_file helper

src/libs/conduit/c/conduit_node.h, src/libs/conduit/c/conduit_node_c.cpp, src/libs/conduit/fortran/conduit_fortran.F90, src/libs/conduit/fortran/conduit_fortran_obj.f90, src/libs/conduit/python/conduit_python.cpp, src/tests/conduit/c/t_c_conduit_node.cpp, src/tests/conduit/fortran/t_f_conduit_node.f90, src/tests/conduit/fortran/t_f_conduit_node_obj.f90, src/tests/conduit/python/t_python_conduit_node.py, src/tests/conduit/python/t_python_conduit_schema.py
adds python wrappers and tests for new node and schema methods supporting child names with embedded slashes
=> py, c, fortran api: add_child, child, remove_child for node and schema

CHANGELOG.md, src/cmake/valgrind.supp, src/libs/conduit/conduit_utils.cpp, src/libs/relay/conduit_relay_io_hdf5.cpp, src/tests/blueprint/t_blueprint_mpi_relay.cpp, src/tests/relay/t_relay_io_hdf5.cpp
=> improve error messages for incompatible hdf5 trees

src/docs/sphinx/blueprint_mesh.rst
The changes in this pull request address the issues outlined in issue #337, which broadly entails revising the Conduit-Blueprint documentation to describe the schema requirements for the `nestsets` section. The following list enumerates the precise list of changes included in this pull request:
=> add nestsets documentation to blueprint docs

src/libs/blueprint/conduit_blueprint_mesh.cpp, src/tests/blueprint/t_blueprint_mesh_verify.cpp
The changes in this pull request fix the `blueprint::mesh::specset::verify` function so that it accepts species information in line with what's described in [the Blueprint documentation](https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#species-sets) instead of strictly `mlarray`-style specifications, as was done previously. This fix allows for specifications like the following to be accepted:
```
specset:
matset: mesh_mats
matset_values:
copper:
cu: [ ... ]
zn: [ ... ]
steel:
fe: [ ... ]
cr: [ ... ]
ni: [ ... ]
mn: [ ... ]
```
=> fix bugs in 'blueprint::mesh::specset::verify'

CHANGELOG.md, src/docs/sphinx/blueprint.rst, src/docs/sphinx/blueprint_mesh.rst, src/docs/sphinx/blueprint_o2mrelation.rst, src/libs/blueprint/CMakeLists.txt, src/libs/blueprint/conduit_blueprint_mesh.cpp, src/libs/blueprint/conduit_blueprint_o2mrelation.cpp, src/libs/blueprint/conduit_blueprint_o2mrelation.hpp, src/libs/blueprint/conduit_blueprint_o2mrelation_examples.cpp, src/libs/blueprint/conduit_blueprint_o2mrelation_examples.hpp, src/tests/blueprint/CMakeLists.txt, src/tests/blueprint/t_blueprint_mesh_verify.cpp, src/tests/blueprint/t_blueprint_o2mrelation_examples.cpp, src/tests/blueprint/t_blueprint_o2mrelation_verify.cpp
The changes in this pull request address #511 and #513 by:
=> add one-to-many indexing schemes, uni-buffer matset support

src/docs/sphinx/blueprint_mesh.rst, src/libs/blueprint/conduit_blueprint_mcarray.cpp, src/libs/blueprint/conduit_blueprint_mcarray.hpp, src/libs/blueprint/conduit_blueprint_mesh.cpp, src/libs/blueprint/conduit_blueprint_mesh_examples_venn.cpp, src/tests/blueprint/t_blueprint_mcarray_verify.cpp, src/tests/blueprint/t_blueprint_mesh_examples.cpp, src/tests/blueprint/t_blueprint_mesh_verify.cpp
The changes in this pull request address #512  by making the following changes:
=> add material-dominant relationship support to blueprint matsets

CHANGELOG.md, src/libs/blueprint/conduit_blueprint_mesh.cpp, src/libs/blueprint/conduit_blueprint_mesh.hpp, src/tests/blueprint/t_blueprint_mesh_verify.cpp
The changes in this pull request directly address #567 by adding property query functions to the `blueprint::mesh::matset` namespace corresponding to the new material set types introduced in #553 and #563.
=> add property queries for new types of matsets

src/libs/blueprint/conduit_blueprint_mesh.cpp, src/libs/blueprint/conduit_blueprint_mesh_examples_venn.cpp
The changes in this pull request address the issues outlined in #575. The new JSON schema for `blueprint::mesh::examples::venn("sparse_by_element", ...)` is:
```
{
"coordsets": 
{
"coords": 
{
"type": {"dtype":"char8_str", "number_of_elements": 12, "offset": 0, "stride": 1, "element_bytes": 1, "endianness": "little"},
"values": 
{
"x": {"dtype":"float64", "number_of_elements": 101, "offset": 0, "stride": 8, "element_bytes": 8, "endianness": "little"},
"y": {"dtype":"float64", "number_of_elements": 101, "offset": 0, "stride": 8, "element_bytes": 8, "endianness": "little"}
},
"params": 
{
"nx": {"dtype":"int64", "number_of_elements": 1, "offset": 0, "stride": 8, "element_bytes": 8, "endianness": "little"},
"ny": {"dtype":"int64", "number_of_elements": 1, "offset": 0, "stride": 8, …
```
=> fix format of 'blueprint::mesh::examples::venn' sparse per-material fields

.gitlab-ci.yml, .gitlab/lassen_jobs.yml, .gitlab/lassen_templates.yml, .gitlab/quartz_jobs.yml, .gitlab/quartz_templates.yml, .gitlab/toolchains_templates.yml, scripts/ci/build-on-lc.sh, scripts/ci/update-uberenv.sh, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/compilers.yaml, scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/compilers.yaml, scripts/uberenv/spack_configs/config.yaml, scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml, scripts/uberenv/uberenv.py
This PR is the "Add CI" part of #517.
Uberenv has been only slightly modified to fix a bug with mirroring.
The spack configuration has been updated based on Ascent one.
The failing jobs in CI are marked as "Allowed failure" when the cause is identified as beyond the scope of this PR.
=> Add CI on LC Gitlab

src/docs/sphinx/blueprint_o2mrelation.rst, src/libs/blueprint/CMakeLists.txt, src/libs/blueprint/conduit_blueprint.hpp, src/libs/blueprint/conduit_blueprint_o2mrelation.cpp, src/libs/blueprint/conduit_blueprint_o2mrelation.hpp, src/libs/blueprint/conduit_blueprint_o2mrelation_iterator.cpp, src/libs/blueprint/conduit_blueprint_o2mrelation_iterator.hpp, src/tests/blueprint/t_blueprint_o2mrelation_examples.cpp
The changes in this pull request add the `blueprint::o2mrelation::O2MIterator` type to Conduit-Blueprint, which facilitates Conduit-style iteration over one-to-many index spaces.
This pull request builds off of #563 and should not be merged until that pull request is finalized. Additionally, this pull request shouldn't be merged until the interface design for the `blueprint::o2mrelation::O2MIterator` type is finalized (see #565 for details).
=> add iterator support for `o2mrelation` structures

scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml
=> Mark MPI as un-buildable on TOSS3

src/docs/sphinx/tutorial_python_basics.rst
I noticed a typo in the documentation for the python tutorial where "from" was written "form." This pr fixes the typo.
=> Fix typo form to from

src/libs/blueprint/conduit_blueprint_mesh.cpp, src/libs/blueprint/conduit_blueprint_mesh_examples.cpp, src/libs/blueprint/conduit_blueprint_mesh_examples_julia.cpp, src/libs/blueprint/conduit_blueprint_mesh_examples_venn.cpp, src/libs/blueprint/conduit_blueprint_o2mrelation_iterator.hpp, src/libs/conduit/conduit_node.cpp, src/libs/conduit/conduit_utils.cpp, src/libs/relay/CMakeLists.txt, src/tests/blueprint/t_blueprint_mesh_generate.cpp, src/tests/thirdparty/CMakeLists.txt
It must be lowercase on case-sensitive file-systems, eg when cross compiling
=> Fix include on case-sensitive-fs

src/libs/blueprint/conduit_blueprint_mesh.cpp
For polygonal topology, propagate `elements` field's `valid` info to parent.
Related to https://github.com/LLNL/conduit/issues/635
The `has_consistent_validity` check (from https://github.com/LLNL/conduit/issues/277 and  https://github.com/LLNL/conduit/pull/283) was failing because the `info` node was inconsistent - topmost `valid` state was `true` despite a subtree (in this case, `elements`) being in a `valid` state of `false`.
=> has_consistent_validity check fix in t_blueprint_mesh_verify
